export const SELECT_PLAYER = 'SELECT_PLAYER';
export const FETCH_PLAYERS = 'FETCH_PLAYERS';

export const SELECT_ROOM = 'SELECT_ROOM';
export const FETCH_ROOMS = 'FETCH_ROOMS';

export const REQUEST_DATA = 'REQUEST_DATA';
export const DATA_REQUEST_ERROR = 'DATA_REQUEST_ERROR';

export const SHOW_PLAYERS_IN_LOBBY = 'SHOW_PLAYERS_IN_LOBBY'
export const SHOW_PLAYERS_IN_ROOM = 'SHOW_PLAYERS_IN_ROOM'
export const SHOW_PLAYERS_IN_GAME = 'SHOW_PLAYERS_IN_GAME'
export const SHOW_ALL_PLAYERS = 'SHOW_ALL_PLAYERS'