export const SELECT_PLAYER = 'SELECT_PLAYER';
export const FETCH_PLAYERS = 'FETCH_PLAYERS';

export const SELECT_ROOM = 'SELECT_ROOM';
export const FETCH_ROOMS = 'FETCH_ROOMS';

export const REQUESTING_PLAYER_DATA = 'REQUESTING_PLAYER_DATA';
export const REQUESTING_ROOM_DATA = 'REQUESTING_ROOM_DATA';
export const DATA_REQUEST_ERROR = 'DATA_REQUEST_ERROR';

export const FILTER_PLAYERS = 'FILTER_PLAYERS';
export const TOGGLE_PLAYER_LIST_ITEM_MODAL = 'TOGGLE_PLAYER_LIST_ITEM_MODAL';

export const TOGGLE_PLAYER_SCREEN_OPTIONS = 'TOGGLE_PLAYER_SCREEN_OPTIONS';

export const VIEW_SHATABRICK = 'VIEW_SHATABRICK';
export const GET_ROOM_DATA_BY_PLAYER_ID = 'GET_ROOM_DATA_BY_PLAYER_ID';
export const GET_ROOM_DATA_BY_ROOM_ID = 'GET_ROOM_DATA_BY_ROOM_ID';