export const SELECT_PLAYER = 'SELECT_PLAYER';
export const FETCH_PLAYERS = 'FETCH_PLAYERS';

export const SELECT_ROOM = 'SELECT_ROOM';
export const FETCH_ROOMS = 'FETCH_ROOMS';

export const REQUEST_DATA = 'REQUEST_DATA';
export const DATA_REQUEST_ERROR = 'DATA_REQUEST_ERROR';

export const FILTER_PLAYERS = 'FILTER_PLAYERS'

export const TOGGLE_PLAYER_SCREEN_OPTIONS = 'TOGGLE_PLAYER_SCREEN_OPTIONS'